### ISSUE TITLE
Following docs results in deprecation notice for gulp.run()

### ISSUE THREAD

**Issue by rupl** [gratimax/gulp-grunt#13]
This is a great plugin, so thanks for creating it! I had no trouble getting set up using your current docs, and everything seems to work just fine. However, I noticed this in my console:

```
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
```

Is there an alternative way of running these tasks? I found this [SO page](http://stackoverflow.com/questions/21905875/gulp-run-is-deprecated-how-do-i-compose-tasks) recommending the use of `gulp.watch` instead, along with another answer that incorrectly recommended `gulp.start` which is [disappearing soon](https://github.com/gulpjs/gulp/issues/505#issuecomment-45379280).

I'd mostly like to figure out the "right way" and I'd be happy to PR the docs back in order once I understand the best way to set the plugin up.

**Comment by erquhart** [comment]
@gratimax the npm package page still shows the old stuff. Thanks for a great tool, btw :)
