### ISSUE TITLE
Configurations not loaded

### ISSUE THREAD

**Issue by XVincentX** [gratimax/gulp-grunt#15]
Hello!
Looks like gulp-grunt plugin does not load configuration, and it may then be unable to run some kind of tasks.

A simple test case can be found [here](https://github.com/angular-ui/bootstrap/blob/master/Gruntfile.js)
gulp-grunt stops while loading claiming cannot find **srcModules** submodule.

V.

**Comment by gratimax** [comment]
Yeah, gulp-grunt does not deal with configuration. Instead, I think the better option is to export the configuration into separate files, if possible:

```js
// config.js
module.exports  = {
  srcModules: // ...
}
```

```js
// Gruntfile.js
var config = require('./config');

grunt.config('srcModules', config.srcModules);
``

The same goes for the Gulpfile. This should pretty much fix your issue, but if it's still inconvenient I can try to add the feature.

**Comment by XVincentX** [comment]
I gave up with gulp and grunt in favor of `npm` as build tool and `webpack` as module loader. But thanks for the interest.

**Comment by gratimax** [comment]
No problem, closing then
