### ISSUE TITLE
Warning: An error occurred while processing a template (srcModules is not defined). 

### ISSUE THREAD

**Issue by dmitriz** [gratimax/gulp-grunt#20]
Trying to use `gulp-grunt` with this `Gruntfile.js` :
https://github.com/angular-ui/bootstrap/blob/master/Gruntfile.js

Terminates with message:

<pre>
Warning: An error occurred while processing a template (srcModules is not defined). Use --force to continue.

Aborted due to warnings.
</pre>

Running `gulp --force` leads to the same effect.

**Comment by bisubus** [comment]
@dmitriz , my guess is that

    require('grunt').option('force', true);

may help for now.

**Comment by gratimax** [comment]
Could you post your gulpfile? I need some more context to try to troubleshoot

**Comment by dmitriz** [comment]
It's been a while. Found an easier way to run it as system command.

**Comment by gratimax** [comment]
Alright, thanks. Closing.
